# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8
podfile: Demo/Podfile
env:
   global:
   - LANG=en_US.UTF-8
   - WORKSPACE="Demo/Demo.xcworkspace"
   - IOS_SCHEME="Demo"
   - IOS_SDK=iphonesimulator10.0

   matrix:
   - DESTINATION="OS=10.0,name=iPhone 6s Plus" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME"

before_install:
 - rvm install ruby-2.3.1
 - brew install swiftlint
 - gem install bundler
 - bundle install
 - bundle exec pod install --project-directory=Demo
 - xcrun instruments -w 'E8DD285C-51EE-4DB5-B326-7E927686EC36' || true

script:
 - bundle exec danger
 - rake test
 - rake carthage_test
 - bash <(curl -s https://codecov.io/bash)
